### ISSUE TITLE
这玩意要怎么运行？

### ISSUE THREAD

**Issue by codervibe** [iceyhexman/onlinetools#26]

**Comment by codervibe** [comment]
Traceback (most recent call last):
  File "/root/software/onlinetools/main.py", line 5, in <module>
    from scanner.app import app
  File "/root/software/onlinetools/scanner/app.py", line 1, in <module>
    from flask import Flask, render_template, \
  File "/usr/local/lib/python3.9/dist-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 25, in <module>
    from . import cli, json
  File "/usr/local/lib/python3.9/dist-packages/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/lib/python3/dist-packages/itsdangerous/__init__.py)

**Comment by codervibe** [comment]
我就问问这玩意要怎么才能运行 
文档里的方法我试过了 我的 python 版本是 python3.9

**Comment by ghost** [comment]
我也比较好奇要怎么才能把项目跑起来。。。

**Comment by uknow3o** [comment]
我也是这个问题，要怎么解决
